produit.1.cle_nom=nom
produit.1.cle_prix=prix
produit.1.type=Ensemble de bricolage ABC - Adhésif
produit.1.details=volume_ml,temps_sechage_sec,resistant_eau

produit.2.cle_nom=nom
produit.2.cle_prix=prix
produit.2.type=Ensemble de bricolage ABC - Outil de coupe
produit.2.details=longueur_lame_cm,lame_remplacable,materiau

produit.3.cle_nom=nom
produit.3.cle_prix=prix
produit.3.type=Ensemble de bricolage ABC - Accessoire de peinture
produit.3.details=taille,feuilles_supplémentaires,material

produit.4.cle_nom=nom
produit.4.cle_prix=prix
produit.4.type=Ensemble de bricolage ABC - Ma catégorie
produit.4.details=attribut1,attribut2,attribut3
